spring.datasource.url=jdbc:mysql://localhost:3306/db-tp3?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wasselaguech@gmail.com
spring.mail.password=cqci qsdq gtbu zpbf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

# === URL de base ===
app.base-url=http://localhost:8080
# Supprimer le warning open-in-view
spring.jpa.open-in-view=false
